export const ROUTES = {
  MAP: '/map',
  PLAYERS: '/players',
  CITIES: '/cities',
  QUESTS: '/quests',
  WORLDS: '/worlds',
  LORES: '/lores',
  NPCS: '/npcs',
  MONSTERS: '/monsters',
  MAP_MARKERS: '/map-markers',
  SESSIONS: '/sessions',
  TIMELINE: '/timeline',
  WIKI: '/wiki',
  DICE: '/dice',
  GM_NOTES: '/gm/notes',
  GM_IMAGES: '/gm/images',
  GM_SHEETS: '/gm/sheets',
  SERVER_ERROR: '/server-error',
} as const;
